# Generated by Django 4.0.2 on 2024-04-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_barcode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='profile_qrcodes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
