# Generated by Django 4.0.2 on 2024-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_remove_barcodescan_barcode_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodescan',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
