# Generated by Django 4.0.2 on 2024-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_barcodescan_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
